#!/usr/bin/env bash

# Launch mpd
if ! pgrep -x "mpd" > /dev/null
then
  mpd ~/.config/mpd/mpd.conf 
fi

# Launch YAMS
if ! pgrep -x "mpdscribble" > /dev/null
then
  mpdscribble
fi

# Launch rmpc
rmpc
