#!/usr/bin/env bash

set -e
set -u

Files () {
  Projects () {
    ghostty -e nvim ~/Projekty/
  }
  NixOS_BTW () {
  	ghostty -e nvim ~/.nixos-btw/
  }
  Dotfiles () {
  	ghostty -e nvim ~/.dotfiles/.config/
  }
  
  declare -a options=(
  	Dotfiles
  	NixOS_BTW
    Projects	
  	"Quit")
  
  choice=$(printf '%s\n' "${options[@]}" | rofi -m 1 -dmenu -i -l 20 -p 'Projects')
  
  if [[ "$choice" == quit ]]; then
  	echo "Program Terminated." && exit 1
  elif [ "$choice" ]; then
  	cfg=$(printf '%s\n' "${choice}" | awk '{print $NF}')
  	"$cfg"
  else
  	echo "Program Terminated." && exit 1
  fi
}

Screenshot () {
if [ "$XDG_SESSION_TYPE" = 'wayland' ]; then
  sleep 1; grim -o HDMI-A-1 -t png -l 5 /mnt/User/Obrazy/screenshots/$(date +'%s_grim.png')
  notify-send "Screenshot Taken"
elif [ "$XDG_SESSION_TYPE" = 'x11' ]; then
  scrot -d 1 -M 0 -q 9
  notify-send "Screenshot Taken"
else
  echo "What?"
fi
}

Themes () {
  ayu () {
    # rofi
    sed -i 's@themes/*.*@themes/ayu"@g' /home/"$USER"/.dotfiles/.config/rofi/config.rasi
    # terminal
    if [ -d /home/"$USER"/.dotfiles/.config/ghostty ]; then
      sed -i 's@theme*.*@theme\ =\ Ayu Mirage@g' /home/"$USER"/.dotfiles/.config/ghostty/config
    elif [ -d /home/"$USER"/.dotfiles/.config/wezterm ]; then
      sed -i 's/color_scheme\ =\ "*.*/color_scheme\ =\ "Ayu Mirage",/g' /home/"$USER"/.dotfiles/.config/wezterm/wezterm.lua 
    else
      echo "Terminal not updated"
    fi
		# editors
		if [ -d /home/"$USER"/.dotfiles/.config/nvim ]; then
      sed -i 's@colorscheme\ *.*@colorscheme ayu-mirage")@g' /home/"$USER"/.dotfiles/.config/nvim/lua/core/colorscheme.lua
			sed -i 's@theme\ =\ *.*@theme\ =\ "ayu",@g' /home/"$USER"/.dotfiles/.config/nvim/lua/plugins/lualine.lua
		elif [ -d /home/"$USER"/.dotfiles/.config/emacs ]; then
			sed -i "s/load-theme\ '*.*/load-theme 'doom-ayu-mirage\ :no-confirm)/g" /home/"$USER"/.dotfiles/.config/emacs/init.el
		else
			echo "Editor not updated"
		fi
    # WMs
		sed -i 's@themes/*.*@themes/ayu.conf@g' /home/"$USER"/.dotfiles/.config/mango/config.conf
    nohup bash -c "mmsg dispatch reload_config"
  }
  catppuccin () {
    # rofi
    sed -i 's@themes/*.*@themes/catppuccin"@g' /home/"$USER"/.dotfiles/.config/rofi/config.rasi
    # terminal
    if [ -d /home/"$USER"/.dotfiles/.config/ghostty ]; then
      sed -i 's@theme*.*@theme\ =\ Catppuccin Mocha@g' /home/"$USER"/.dotfiles/.config/ghostty/config
    elif [ -d /home/"$USER"/.dotfiles/.config/wezterm ]; then
      sed -i 's/color_scheme\ =\ "*.*/color_scheme\ =\ "Catppuccin Mocha",/g' /home/"$USER"/.dotfiles/.config/wezterm/wezterm.lua 
    else
      echo "Terminal not updated"
    fi
		# editors
		if [ -d /home/"$USER"/.dotfiles/.config/nvim ]; then
      sed -i 's@colorscheme\ *.*@colorscheme catppuccin")@g' /home/"$USER"/.dotfiles/.config/nvim/lua/core/colorscheme.lua
      sed -i 's@theme\ =\ *.*@theme\ =\ "catppuccin-nvim",@g' /home/"$USER"/.dotfiles/.config/nvim/lua/plugins/lualine.lua
		elif [ -d /home/"$USER"/.dotfiles/.config/emacs ]; then
      sed -i "s/load-theme\ '*.*/load-theme 'catppuccin\ :no-confirm)/g" /home/"$USER"/.dotfiles/.config/emacs/init.el
		else
			echo "Editor not updated"
		fi
    # WMs
		sed -i 's@themes/*.*@themes/catppuccin.conf@g' /home/"$USER"/.dotfiles/.config/mango/config.conf
    nohup bash -c "mmsg dispatch reload_config"
  }
  dracula () {
    # rofi
    sed -i 's@themes/*.*@themes/dracula"@g' /home/"$USER"/.dotfiles/.config/rofi/config.rasi
    # terminal
    if [ -d /home/"$USER"/.dotfiles/.config/ghostty ]; then
      sed -i 's@theme*.*@theme\ =\ Dracula@g' /home/"$USER"/.dotfiles/.config/ghostty/config
    elif [ -d /home/"$USER"/.dotfiles/.config/wezterm ]; then
      sed -i 's/color_scheme\ =\ "*.*/color_scheme\ =\ "Dracula (Official)",/g' /home/"$USER"/.dotfiles/.config/wezterm/wezterm.lua 
    else
      echo "Terminal not updated"
    fi
		# editors
		if [ -d /home/"$USER"/.dotfiles/.config/nvim ]; then
      sed -i 's@colorscheme\ *.*@colorscheme dracula")@g' /home/"$USER"/.dotfiles/.config/nvim/lua/core/colorscheme.lua
      sed -i 's@theme\ =\ *.*@theme\ =\ "dracula",@g' /home/"$USER"/.dotfiles/.config/nvim/lua/plugins/lualine.lua
		elif [ -d /home/"$USER"/.dotfiles/.config/emacs ]; then
      sed -i "s/load-theme\ '*.*/load-theme 'doom-dracula\ :no-confirm)/g" /home/"$USER"/.dotfiles/.config/emacs/init.el
		else
			echo "Editor not updated"
		fi
		# WMs
		sed -i 's@themes/*.*@themes/dracula.conf@g' /home/"$USER"/.dotfiles/.config/mango/config.conf
    nohup bash -c "mmsg dispatch reload_config"
  }
  everforest () {
    # rofi
    sed -i 's@themes/*.*@themes/everforest"@g' /home/"$USER"/.dotfiles/.config/rofi/config.rasi
    # terminal
    if [ -d /home/"$USER"/.dotfiles/.config/ghostty ]; then
      sed -i 's@theme*.*@theme\ =\ Everforest\ Dark\ Hard@g' /home/"$USER"/.dotfiles/.config/ghostty/config
    elif [ -d /home/"$USER"/.dotfiles/.config/wezterm ]; then
      sed -i 's/color_scheme\ =\ "*.*/color_scheme\ =\ "Everforest Dark (Gogh)",/g' /home/"$USER"/.dotfiles/.config/wezterm/wezterm.lua 
    else
      echo "Terminal not updated"
    fi
		# editors
		if [ -d /home/"$USER"/.dotfiles/.config/nvim ]; then
      sed -i 's@colorscheme\ *.*@colorscheme everforest")@g' /home/"$USER"/.dotfiles/.config/nvim/lua/core/colorscheme.lua
      sed -i 's@theme\ =\ *.*@theme\ =\ "everforest",@g' /home/"$USER"/.dotfiles/.config/nvim/lua/plugins/lualine.lua
		elif [ -d /home/"$USER"/.dotfiles/.config/emacs ]; then
      sed -i "s/load-theme\ '*.*/load-theme 'everforest-hard-dark\ :no-confirm)/g" /home/"$USER"/.dotfiles/.config/emacs/init.el
		else
			echo "Editor not updated"
		fi
    # WMs
		sed -i 's@themes/*.*@themes/everforest.conf@g' /home/"$USER"/.dotfiles/.config/mango/config.conf
    nohup bash -c "mmsg dispatch reload_config"
  }
  gruvbox () {
    # rofi
    sed -i 's@themes/*.*@themes/gruvbox"@g' /home/"$USER"/.dotfiles/.config/rofi/config.rasi
    # terminal
    if [ -d /home/"$USER"/.dotfiles/.config/ghostty ]; then
      sed -i 's@theme*.*@theme\ =\ Gruvbox\ Dark@g' /home/"$USER"/.dotfiles/.config/ghostty/config
    elif [ -d /home/"$USER"/.dotfiles/.config/wezterm ]; then
      sed -i 's/color_scheme\ =\ "*.*/color_scheme\ =\ "GruvboxDark",/g' /home/"$USER"/.dotfiles/.config/wezterm/wezterm.lua 
    else
      echo "Terminal not updated"
    fi
		# editors
		if [ -d /home/"$USER"/.dotfiles/.config/nvim ]; then
      sed -i 's@colorscheme\ *.*@colorscheme gruvbox")@g' /home/"$USER"/.dotfiles/.config/nvim/lua/core/colorscheme.lua
      sed -i 's@theme\ =\ *.*@theme\ =\ "gruvbox",@g' /home/"$USER"/.dotfiles/.config/nvim/lua/plugins/lualine.lua
		elif [ -d /home/"$USER"/.dotfiles/.config/emacs ]; then
      sed -i "s/load-theme\ '*.*/load-theme 'doom-gruvbox\ :no-confirm)/g" /home/"$USER"/.dotfiles/.config/emacs/init.el
		else
			echo "Editor not updated"
		fi
    # WMs
		sed -i 's@themes/*.*@themes/gruvbox.conf@g' /home/"$USER"/.dotfiles/.config/mango/config.conf
    nohup bash -c "mmsg dispatch reload_config"
  }
  kanagawa () {
    # rofi
    sed -i 's@themes/*.*@themes/kanagawa"@g' /home/"$USER"/.dotfiles/.config/rofi/config.rasi
    # terminal
    if [ -d /home/"$USER"/.dotfiles/.config/ghostty ]; then
      sed -i 's@theme*.*@theme\ =\ Kanagawa\ Wave@g' /home/"$USER"/.dotfiles/.config/ghostty/config
    elif [ -d /home/"$USER"/.dotfiles/.config/wezterm ]; then
      sed -i 's/color_scheme\ =\ "*.*/color_scheme\ =\ "Kanagawa (Gogh)",/g' /home/"$USER"/.dotfiles/.config/wezterm/wezterm.lua 
    else
      echo "Terminal not updated"
    fi
		# editors
		if [ -d /home/"$USER"/.dotfiles/.config/nvim ]; then
      sed -i 's@colorscheme\ *.*@colorscheme kanagawa-wave")@g' /home/"$USER"/.dotfiles/.config/nvim/lua/core/colorscheme.lua
      sed -i 's@theme\ =\ *.*@theme\ =\ "auto",@g' /home/"$USER"/.dotfiles/.config/nvim/lua/plugins/lualine.lua
		elif [ -d /home/"$USER"/.dotfiles/.config/emacs ]; then
      sed -i "s/load-theme\ '*.*/load-theme 'kanagawa-wave\ :no-confirm)/g" /home/"$USER"/.dotfiles/.config/emacs/init.el
		else
			echo "Editor not updated"
		fi
    # WMs
		sed -i 's@themes/*.*@themes/kanagawa.conf@g' /home/"$USER"/.dotfiles/.config/mango/config.conf
    nohup bash -c "mmsg dispatch reload_config"
  }
  modus () {
    # rofi
    sed -i 's@themes/*.*@themes/modus"@g' /home/"$USER"/.dotfiles/.config/rofi/config.rasi
    # terminal
    if [ -d /home/"$USER"/.dotfiles/.config/ghostty ]; then
      sed -i 's@theme*.*@theme\ =\ Modus Vivendi@g' /home/"$USER"/.dotfiles/.config/ghostty/config
    elif [ -d /home/"$USER"/.dotfiles/.config/wezterm ]; then
      sed -i 's/color_scheme\ =\ "*.*/color_scheme\ =\ "Modus-Vivendi",/g' /home/"$USER"/.dotfiles/.config/wezterm/wezterm.lua 
    else
      echo "Terminal not updated"
    fi
		# editors
		if [ -d /home/"$USER"/.dotfiles/.config/nvim ]; then
      sed -i 's@colorscheme\ *.*@colorscheme modus")@g' /home/"$USER"/.dotfiles/.config/nvim/lua/core/colorscheme.lua
      sed -i 's@theme\ =\ *.*@theme\ =\ "modus",@g' /home/"$USER"/.dotfiles/.config/nvim/lua/plugins/lualine.lua
		elif [ -d /home/"$USER"/.dotfiles/.config/emacs ]; then
      sed -i "s/load-theme\ '*.*/load-theme 'modus-vivevndi\ :no-confirm)/g" /home/"$USER"/.dotfiles/.config/emacs/init.el
		else
			echo "Editor not updated"
		fi
    # WMs
		sed -i 's@themes/*.*@themes/modus.conf@g' /home/"$USER"/.dotfiles/.config/mango/config.conf
    nohup bash -c "mmsg dispatch reload_config"
  }
  onedark () {
    # rofi
    sed -i 's@themes/*.*@themes/onedark"@g' /home/"$USER"/.dotfiles/.config/rofi/config.rasi
    # terminal
    if [ -d /home/"$USER"/.dotfiles/.config/ghostty ]; then
      sed -i 's@theme*.*@theme\ =\ One Half Dark@g' /home/"$USER"/.dotfiles/.config/ghostty/config
    elif [ -d /home/"$USER"/.dotfiles/.config/wezterm ]; then
      sed -i 's/color_scheme\ =\ "*.*/color_scheme\ =\ "OneHalfDark",/g' /home/"$USER"/.dotfiles/.config/wezterm/wezterm.lua 
    else
      echo "Terminal not updated"
    fi
		# editors
		if [ -d /home/"$USER"/.dotfiles/.config/nvim ]; then
      sed -i 's@colorscheme\ *.*@colorscheme onedark")@g' /home/"$USER"/.dotfiles/.config/nvim/lua/core/colorscheme.lua
      sed -i 's@theme\ =\ *.*@theme\ =\ "onedark",@g' /home/"$USER"/.dotfiles/.config/nvim/lua/plugins/lualine.lua
		elif [ -d /home/"$USER"/.dotfiles/.config/emacs ]; then
      sed -i "s/load-theme\ '*.*/load-theme 'doom-one\ :no-confirm)/g" /home/"$USER"/.dotfiles/.config/emacs/init.el
		else
			echo "Editor not updated"
		fi
    # WMs
		sed -i 's@themes/*.*@themes/onedark.conf@g' /home/"$USER"/.dotfiles/.config/mango/config.conf
    nohup bash -c "mmsg dispatch reload_config"
  }
  poimandres () {
    # rofi
    sed -i 's@themes/*.*@themes/poimandres"@g' /home/"$USER"/.dotfiles/.config/rofi/config.rasi
    # terminal
    if [ -d /home/"$USER"/.dotfiles/.config/ghostty ]; then
      sed -i 's@theme*.*@theme\ =\ Poimandres@g' /home/"$USER"/.dotfiles/.config/ghostty/config
    elif [ -d /home/"$USER"/.dotfiles/.config/wezterm ]; then
      sed -i 's/color_scheme\ =\ "*.*/color_scheme\ =\ "Poimandres",/g' /home/"$USER"/.dotfiles/.config/wezterm/wezterm.lua 
    else
      echo "Terminal not updated"
    fi
		# editors
		if [ -d /home/"$USER"/.dotfiles/.config/nvim ]; then
      sed -i 's@colorscheme\ *.*@colorscheme poimandres")@g' /home/"$USER"/.dotfiles/.config/nvim/lua/core/colorscheme.lua
      sed -i 's@theme\ =\ *.*@theme\ =\ "poimandres",@g' /home/"$USER"/.dotfiles/.config/nvim/lua/plugins/lualine.lua
		elif [ -d /home/"$USER"/.dotfiles/.config/emacs ]; then
      sed -i "s/load-theme\ '*.*/load-theme 'poimandres\ :no-confirm)/g" /home/"$USER"/.dotfiles/.config/emacs/init.el
		else
			echo "Editor not updated"
		fi
    # WMs
		sed -i 's@themes/*.*@themes/poimandres.conf@g' /home/"$USER"/.dotfiles/.config/mango/config.conf
    nohup bash -c "mmsg dispatch reload_config"
  }
  spacegray () {
    # rofi
    sed -i 's@themes/*.*@themes/spacegray"@g' /home/"$USER"/.dotfiles/.config/rofi/config.rasi
		# terminal
    if [ -d /home/"$USER"/.dotfiles/.config/ghostty ]; then
      sed -i 's@theme*.*@theme\ =\ Spacegray@g' /home/"$USER"/.dotfiles/.config/ghostty/config
    elif [ -d /home/"$USER"/.dotfiles/.config/wezterm ]; then
      sed -i 's/color_scheme\ =\ "*.*/color_scheme\ =\ "SpaceGray",/g' /home/"$USER"/.dotfiles/.config/wezterm/wezterm.lua 
    else
      echo "Terminal not updated"
    fi
		# editors
		if [ -d /home/"$USER"/.dotfiles/.config/nvim ]; then
      sed -i 's@colorscheme\ *.*@colorscheme nordic")@g' /home/"$USER"/.dotfiles/.config/nvim/lua/core/colorscheme.lua
      sed -i 's@theme\ =\ *.*@theme\ =\ "auto",@g' /home/"$USER"/.dotfiles/.config/nvim/lua/plugins/lualine.lua
		elif [ -d /home/"$USER"/.dotfiles/.config/emacs ]; then
      sed -i "s/load-theme\ '*.*/load-theme 'doom-spacegrey\ :no-confirm)/g" /home/"$USER"/.dotfiles/.config/emacs/init.el
		else
			echo "Editor not updated"
		fi
    # WMs
		sed -i 's@themes/*.*@themes/spacegray.conf@g' /home/"$USER"/.dotfiles/.config/mango/config.conf
    nohup bash -c "mmsg dispatch reload_config"
  }
  tokyonight () {
    # rofi
    sed -i 's@themes/*.*@themes/tokyonight"@g' /home/"$USER"/.dotfiles/.config/rofi/config.rasi
    # terminal
    if [ -d /home/"$USER"/.dotfiles/.config/ghostty ]; then
      sed -i 's@theme*.*@theme\ =\ TokyoNight@g' /home/"$USER"/.dotfiles/.config/ghostty/config
    elif [ -d /home/"$USER"/.dotfiles/.config/wezterm ]; then
      sed -i 's/color_scheme\ =\ "*.*/color_scheme\ =\ "Tokyo Night",/g' /home/"$USER"/.dotfiles/.config/wezterm/wezterm.lua 
    else
      echo "Terminal not updated"
    fi
		# editors
		if [ -d /home/"$USER"/.dotfiles/.config/nvim ]; then
      sed -i 's@colorscheme\ *.*@colorscheme tokyonight")@g' /home/"$USER"/.dotfiles/.config/nvim/lua/core/colorscheme.lua
      sed -i 's@theme\ =\ *.*@theme\ =\ "tokyonight",@g' /home/"$USER"/.dotfiles/.config/nvim/lua/plugins/lualine.lua
		elif [ -d /home/"$USER"/.dotfiles/.config/emacs ]; then
      sed -i "s/load-theme\ '*.*/load-theme 'doom-tokyo-night\ :no-confirm)/g" /home/"$USER"/.dotfiles/.config/emacs/init.el
		else
			echo "Editor not updated"
		fi
    # WMs
		sed -i 's@themes/*.*@themes/tokyonight.conf@g' /home/"$USER"/.dotfiles/.config/mango/config.conf
    nohup bash -c "mmsg dispatch reload_config"
  }
  declare -a options=(
  ayu
  catppuccin
  dracula
  everforest
  gruvbox
  kanagawa
  modus
  onedark
  poimandres
  spacegray
  tokyonight
  "quit"
  )
  choice=$(printf '%s\n' "${options[@]}" | rofi -m 1 -dmenu -i -l 20 -p 'Utilities')
  if [[ "$choice" == quit ]]; then
    echo "Program Terminated." && exit 1
  elif [ "$choice" ]; then
    cfg=$(printf '%s\n' "${choice}" | awk '{print $NF}')
    "$cfg"
  else
    echo "What?" && exit 1
  fi
}

declare -a options=(
Files
Screenshot
Themes
"Quit"
)

choice=$(printf '%s\n' "${options[@]}" | rofi -m 1 -dmenu -i -l 20 -p 'Utilities')

if [[ "$choice" == quit ]]; then
	echo "Program Terminated." && exit 1
elif [ "$choice" ]; then
	cfg=$(printf '%s\n' "${choice}" | awk '{print $NF}')
	"$cfg"
else
	echo "Program Terminated." && exit 1
fi
