#!/usr/bin/env bash

set -e
set -u


Wallpaper () {
if [ $XDG_SESSION_TYPE = 'wayland' ]; then
	swaybg -i $(shuf -e -n1 $HOME/Obrazy/tapety/*) & disown
elif [ $XDG_SESSION_TYPE = 'x11' ]; then
  shuf -e -n1 $HOME/Obrazy/tapety/* | xargs feh --bg-fill
else
  echo "What?"
fi
}

Themes () {
  ayu () {
    # btop
    sed -i 's@themes/*.*@themes/ayu.theme"@g' /home/$USER/.dotfiles/.config/btop/btop.conf
    # emacs
    sed -i "s/load-theme\ '*.*/load-theme 'doom-ayu-mirage\ :no-confirm)/g" /home/$USER/.dotfiles/.config/emacs/init.el
    # ghostty
    sed -i 's@themes/*.*@themes/Ayu Mirage@g' /home/$USER/.dotfiles/.config/ghostty/config
    # rofi
    sed -i 's@themes/*.*@themes/ayu"@g' /home/$USER/.dotfiles/.config/rofi/config.rasi
    # rmpc
    sed -i 's/theme:\ Some("*.*"),/theme:\ Some("ayu"),/g' /home/$USER/.dotfiles/.config/rmpc/config.ron
    # WMs
    if [ $XDG_CURRENT_DESKTOP = 'hyprland' ]; then
			sed -i 's@col.active_border*.*@col.active_border\ =\ rgba(FFCC66ff)@g' /home/$USER/.dotfiles/.config/hypr/hyprland.conf
			sed -i 's@col.inactive_border*.*@col.inactive_border\ =\ rgba(444A55ff)@g' /home/$USER/.dotfiles/.config/hypr/hyprland.conf
			sed -i 's@color*.*@color\ =\ rgba(323843ff)@g' /home/$USER/.dotfiles/.config/hypr/hyprland.conf
			sed -i 's@wallpapers/*.*@wallpapers/ayu.png@g' /home/$USER/.dotfiles/.config/hypr/hyprland.conf
			sed -i 's@wallpapers/*.*@wallpapers/ayu.png@g' /home/$USER/.dotfiles/.config/hypr/hyprlock.conf
			sed -i 's@themes/*.*@themes/ayu.css";@g' /home/$USER/.dotfiles/.config/waybar/style.css
      nohup bash -c "pkill swaybg; swaybg -i ~/.dotfiles/wallpapers/ayu.png &"
      nohup bash -c "killall waybar && waybar & disown"
    elif [ $XDG_CURRENT_DESKTOP = 'qtile' ]; then
			sed -i 's/themes.*\ import\ colors/themes.ayu\ import\ colors/g' /home/$USER/.dotfiles/.config/qtile/config.py
			sed -i 's@wallpapers/*.*@wallpapers/ayu.png",@g' /home/$USER/.dotfiles/.config/qtile/config.py
			sed -i 's@xresources/*.*@xresources/ayu"@g' /home/$USER/.dotfiles/.Xresources
      qtile cmd-obj -o cmd -f reload_config
		elif  [ $XDG_CURRENT_DESKTOP = 'mango' ]; then
			sed -i 's@themes/*.*@themes/ayu.conf@g' /home/$USER/.dotfiles/.config/mango/config.conf
			sed -i 's@themes/*.*@themes/ayu.css";@g' /home/$USER/.dotfiles/.config/waybar/style.css
      nohup bash -c "pkill swaybg; swaybg -i ~/.dotfiles/wallpapers/ayu.png &"
      nohup bash -c "killall waybar && waybar & disown"
    else
      echo "What?"
    fi
    # dunst
    sed -i 's@background\ =\ "#*.*@background\ =\ "#1F2430"@g' /home/$USER/.dotfiles/.config/dunst/dunstrc
    sed -i 's@foreground\ =\ "#*.*@foreground\ =\ "#CCCAC2"@g' /home/$USER/.dotfiles/.config/dunst/dunstrc
    sed -i 's@frame_color\ =\ "#*.*@frame_color\ =\ "#FFCC66"@g' /home/$USER/.dotfiles/.config/dunst/dunstrc
    killall -e dunst & sleep 1; dunstify "Theme switched to Ayu" &
  }
  catppuccin () {
    # btop
    sed -i 's@themes/*.*@themes/catppuccin.theme"@g' /home/$USER/.dotfiles/.config/btop/btop.conf
    # emacs
    sed -i "s/load-theme\ '*.*/load-theme 'catppuccin\ :no-confirm)/g" /home/$USER/.dotfiles/.config/emacs/init.el
    # ghostty
    sed -i 's@themes/*.*@themes/Catppuccin Mocha@g' /home/$USER/.dotfiles/.config/ghostty/config
    # rofi
    sed -i 's@themes/*.*@themes/catppuccin"@g' /home/$USER/.dotfiles/.config/rofi/config.rasi
    # rmpc
    sed -i 's/theme:\ Some("*.*"),/theme:\ Some("catppuccin"),/g' /home/$USER/.dotfiles/.config/rmpc/config.ron
    # WMs
    if [ $XDG_CURRENT_DESKTOP = 'hyprland' ]; then
			sed -i 's@col.active_border*.*@col.active_border\ =\ rgba(cba6f7ff)@g' /home/$USER/.dotfiles/.config/hypr/hyprland.conf
			sed -i 's@col.inactive_border*.*@col.inactive_border\ =\ rgba(45475aff)@g' /home/$USER/.dotfiles/.config/hypr/hyprland.conf
			sed -i 's@color*.*@color\ =\ rgba(313244ff)@g' /home/$USER/.dotfiles/.config/hypr/hyprland.conf
			sed -i 's@wallpapers/*.*@wallpapers/catppuccin.png@g' /home/$USER/.dotfiles/.config/hypr/hyprland.conf
			sed -i 's@wallpapers/*.*@wallpapers/catppuccin.png@g' /home/$USER/.dotfiles/.config/hypr/hyprlock.conf
			sed -i 's@themes/*.*@themes/catppuccin.css";@g' /home/$USER/.dotfiles/.config/waybar/style.css
      nohup bash -c "pkill swaybg; swaybg -i ~/.dotfiles/wallpapers/catppuccin.png &"
      nohup bash -c "killall waybar && waybar & disown"
    elif [ $XDG_CURRENT_DESKTOP = 'qtile' ]; then
			sed -i 's/themes.*\ import\ colors/themes.catppuccin\ import\ colors/g' /home/$USER/.dotfiles/.config/qtile/config.py
			sed -i 's@wallpapers/*.*@wallpapers/catppuccin.png",@g' /home/$USER/.dotfiles/.config/qtile/config.py
			sed -i 's@xresources/*.*@xresources/catppuccin"@g' /home/$USER/.dotfiles/.Xresources
      qtile cmd-obj -o cmd -f reload_config
		elif  [ $XDG_CURRENT_DESKTOP = 'mango' ]; then
			sed -i 's@themes/*.*@themes/catppuccin.conf@g' /home/$USER/.dotfiles/.config/mango/config.conf
			sed -i 's@themes/*.*@themes/catppuccin.css";@g' /home/$USER/.dotfiles/.config/waybar/style.css
      nohup bash -c "pkill swaybg; swaybg -i ~/.dotfiles/wallpapers/catppuccin.png &"
      nohup bash -c "killall waybar && waybar & disown"
    else
      echo "What?"
    fi
    # dunst
    sed -i 's@background\ =\ "#*.*@background\ =\ "#1e1e2e"@g' /home/$USER/.dotfiles/.config/dunst/dunstrc
    sed -i 's@foreground\ =\ "#*.*@foreground\ =\ "#cdd6f4"@g' /home/$USER/.dotfiles/.config/dunst/dunstrc
    sed -i 's@frame_color\ =\ "#*.*@frame_color\ =\ "#cba6f7"@g' /home/$USER/.dotfiles/.config/dunst/dunstrc
    killall -e dunst & sleep 1; dunstify "Theme switched to Catppuccin" &
  }
  dracula () {
    # btop
    sed -i 's@themes/*.*@themes/dracula.theme"@g' /home/$USER/.dotfiles/.config/btop/btop.conf
    # emacs
    sed -i "s/load-theme\ '*.*/load-theme 'doom-dracula\ :no-confirm)/g" /home/$USER/.dotfiles/.config/emacs/init.el
    # ghostty
    sed -i 's@themes/*.*@themes/Dracula@g' /home/$USER/.dotfiles/.config/ghostty/config
    # rofi
    sed -i 's@themes/*.*@themes/dracula"@g' /home/$USER/.dotfiles/.config/rofi/config.rasi
    # rmpc
    sed -i 's/theme:\ Some("*.*"),/theme:\ Some("dracula"),/g' /home/$USER/.dotfiles/.config/rmpc/config.ron
		# WMs
    if [ $XDG_CURRENT_DESKTOP = 'hyprland' ]; then
			sed -i 's@col.active_border*.*@col.active_border\ =\ rgba(5AF78Eff)@g' /home/$USER/.dotfiles/.config/hypr/hyprland.conf
			sed -i 's@col.inactive_border*.*@col.inactive_border\ =\ rgba(4D4D4Dff)@g' /home/$USER/.dotfiles/.config/hypr/hyprland.conf
			sed -i 's@color*.*@color\ =\ rgba(3D3F4Aff)@g' /home/$USER/.dotfiles/.config/hypr/hyprland.conf
			sed -i 's@wallpapers/*.*@wallpapers/dracula.png@g' /home/$USER/.dotfiles/.config/hypr/hyprland.conf
			sed -i 's@wallpapers/*.*@wallpapers/dracula.png@g' /home/$USER/.dotfiles/.config/hypr/hyprlock.conf
			sed -i 's@themes/*.*@themes/dracula.css";@g' /home/$USER/.dotfiles/.config/waybar/style.css
      nohup bash -c "pkill swaybg; swaybg -i ~/.dotfiles/wallpapers/dracula.png &"
      nohup bash -c "killall waybar && waybar & disown"
    elif [ $XDG_CURRENT_DESKTOP = 'qtile' ]; then
			sed -i 's/themes.*\ import\ colors/themes.dracula\ import\ colors/g' /home/$USER/.dotfiles/.config/qtile/config.py
			sed -i 's@wallpapers/*.*@wallpapers/dracula.png",@g' /home/$USER/.dotfiles/.config/qtile/config.py
			sed -i 's@xresources/*.*@xresources/dracula"@g' /home/$USER/.dotfiles/.Xresources
      qtile cmd-obj -o cmd -f reload_config
		elif  [ $XDG_CURRENT_DESKTOP = 'mango' ]; then
			sed -i 's@themes/*.*@themes/dracula.conf@g' /home/$USER/.dotfiles/.config/mango/config.conf
			sed -i 's@themes/*.*@themes/dracula.css";@g' /home/$USER/.dotfiles/.config/waybar/style.css
      nohup bash -c "pkill swaybg; swaybg -i ~/.dotfiles/wallpapers/dracula.png &"
      nohup bash -c "killall waybar && waybar & disown"
    else
      echo "What?"
    fi
    # dunst
    sed -i 's@background\ =\ "#*.*@background\ =\ "#282A36"@g' /home/$USER/.dotfiles/.config/dunst/dunstrc
    sed -i 's@foreground\ =\ "#*.*@foreground\ =\ "#E6E6E6"@g' /home/$USER/.dotfiles/.config/dunst/dunstrc
    sed -i 's@frame_color\ =\ "#*.*@frame_color\ =\ "#5AF78E"@g' /home/$USER/.dotfiles/.config/dunst/dunstrc
    killall -e dunst & sleep 1; dunstify "Theme switched to Dracula" &
  }
  everforest () {
    # btop
    sed -i 's@themes/*.*@themes/everforest-dark-hard.theme"@g' /home/$USER/.dotfiles/.config/btop/btop.conf
    # emacs
    sed -i "s/load-theme\ '*.*/load-theme 'everforest-hard-dark\ :no-confirm)/g" /home/$USER/.dotfiles/.config/emacs/init.el
    # ghostty
    sed -i 's@themes/*.*@themes/Everforest\ Dark\ Hard@g' /home/$USER/.dotfiles/.config/ghostty/config
    # rofi
    sed -i 's@themes/*.*@themes/everforest"@g' /home/$USER/.dotfiles/.config/rofi/config.rasi
    # rmpc
    sed -i 's/theme:\ Some("*.*"),/theme:\ Some("everforest"),/g' /home/$USER/.dotfiles/.config/rmpc/config.ron
    # WMs
    if [ $XDG_CURRENT_DESKTOP = 'hyprland' ]; then
			sed -i 's@col.active_border*.*@col.active_border\ =\ rgba(a7c080ff)@g' /home/$USER/.dotfiles/.config/hypr/hyprland.conf
			sed -i 's@col.inactive_border*.*@col.inactive_border\ =\ rgba(272e33ff)@g' /home/$USER/.dotfiles/.config/hypr/hyprland.conf
			sed -i 's@color*.*@color\ =\ rgba(1e2326ff)@g' /home/$USER/.dotfiles/.config/hypr/hyprland.conf
			sed -i 's@wallpapers/*.*@wallpapers/everforest.png@g' /home/$USER/.dotfiles/.config/hypr/hyprland.conf
			sed -i 's@wallpapers/*.*@wallpapers/everforest.png@g' /home/$USER/.dotfiles/.config/hypr/hyprlock.conf
			sed -i 's@themes/*.*@themes/everforest.css";@g' /home/$USER/.dotfiles/.config/waybar/style.css
      nohup bash -c "pkill swaybg; swaybg -i ~/.dotfiles/wallpapers/everforest.png &"
      nohup bash -c "killall waybar && waybar & disown"
    elif [ $XDG_CURRENT_DESKTOP = 'qtile' ]; then
			sed -i 's/themes.*\ import\ colors/themes.everforest\ import\ colors/g' /home/$USER/.dotfiles/.config/qtile/config.py
			sed -i 's@wallpapers/*.*@wallpapers/everforest.png",@g' /home/$USER/.dotfiles/.config/qtile/config.py
			sed -i 's@xresources/*.*@xresources/everforest"@g' /home/$USER/.dotfiles/.Xresources
      qtile cmd-obj -o cmd -f reload_config
		elif  [ $XDG_CURRENT_DESKTOP = 'mango' ]; then
			sed -i 's@themes/*.*@themes/everforest.conf@g' /home/$USER/.dotfiles/.config/mango/config.conf
			sed -i 's@themes/*.*@themes/everforest.css";@g' /home/$USER/.dotfiles/.config/waybar/style.css
      nohup bash -c "pkill swaybg; swaybg -i ~/.dotfiles/wallpapers/everforest.png &"
      nohup bash -c "killall waybar && waybar & disown"
    else
      echo "What?"
    fi
    # dunst
    sed -i 's@background\ =\ "#*.*@background\ =\ "#1e2326"@g' /home/$USER/.dotfiles/.config/dunst/dunstrc
    sed -i 's@foreground\ =\ "#*.*@foreground\ =\ "#d3c6aa"@g' /home/$USER/.dotfiles/.config/dunst/dunstrc
    sed -i 's@frame_color\ =\ "#*.*@frame_color\ =\ "#a7c080"@g' /home/$USER/.dotfiles/.config/dunst/dunstrc
    killall -e dunst & sleep 1; dunstify "Theme switched to everforest" &
  }
  grayscale () {
    # btop
    sed -i 's@themes/*.*@themes/greyscale.theme"@g' /home/$USER/.dotfiles/.config/btop/btop.conf
    # emacs
    sed -i "s/load-theme\ '*.*/load-theme 'real-mono-dark\ :no-confirm)/g" /home/$USER/.dotfiles/.config/emacs/init.el
    # ghostty
    sed -i 's@themes/*.*@themes/studio1804@g' /home/$USER/.dotfiles/.config/ghostty/config
    # rofi
    sed -i 's@themes/*.*@themes/grayscale"@g' /home/$USER/.dotfiles/.config/rofi/config.rasi
    # rmpc
    sed -i 's/theme:\ Some("*.*"),/theme:\ Some("grayscale"),/g' /home/$USER/.dotfiles/.config/rmpc/config.ron
    # WMs
    if [ $XDG_CURRENT_DESKTOP = 'hyprland' ]; then
			sed -i 's@col.active_border*.*@col.active_border\ =\ rgba(ccccccff)@g' /home/$USER/.dotfiles/.config/hypr/hyprland.conf
			sed -i 's@col.inactive_border*.*@col.inactive_border\ =\ rgba(727272ff)@g' /home/$USER/.dotfiles/.config/hypr/hyprland.conf
			sed -i 's@color*.*@color\ =\ rgba(393939ff)@g' /home/$USER/.dotfiles/.config/hypr/hyprland.conf
			sed -i 's@wallpapers/*.*@wallpapers/grayscale.png@g' /home/$USER/.dotfiles/.config/hypr/hyprland.conf
			sed -i 's@wallpapers/*.*@wallpapers/grayscale.png@g' /home/$USER/.dotfiles/.config/hypr/hyprlock.conf
			sed -i 's@themes/*.*@themes/grayscale.css";@g' /home/$USER/.dotfiles/.config/waybar/style.css
      nohup bash -c "pkill swaybg; swaybg -i ~/.dotfiles/wallpapers/grayscale.png &"
      nohup bash -c "killall waybar && waybar & disown"
    elif [ $XDG_CURRENT_DESKTOP = 'qtile' ]; then
			sed -i 's/themes.*\ import\ colors/themes.grayscale\ import\ colors/g' /home/$USER/.dotfiles/.config/qtile/config.py
			sed -i 's@wallpapers/*.*@wallpapers/grayscale.png",@g' /home/$USER/.dotfiles/.config/qtile/config.py
			sed -i 's@xresources/*.*@xresources/grayscale"@g' /home/$USER/.dotfiles/.Xresources
      qtile cmd-obj -o cmd -f reload_config
		elif  [ $XDG_CURRENT_DESKTOP = 'mango' ]; then
			sed -i 's@themes/*.*@themes/grayscale.conf@g' /home/$USER/.dotfiles/.config/mango/config.conf
			sed -i 's@themes/*.*@themes/grayscale.css";@g' /home/$USER/.dotfiles/.config/waybar/style.css
      nohup bash -c "pkill swaybg; swaybg -i ~/.dotfiles/wallpapers/grayscale.png &"
      nohup bash -c "killall waybar && waybar & disown"
    else
      echo "What?"
    fi
    # dunst
    sed -i 's@background\ =\ "#*.*@background\ =\ "#080808"@g' /home/$USER/.dotfiles/.config/dunst/dunstrc
    sed -i 's@foreground\ =\ "#*.*@foreground\ =\ "#cccccc"@g' /home/$USER/.dotfiles/.config/dunst/dunstrc
    sed -i 's@frame_color\ =\ "#*.*@frame_color\ =\ "#7a7a7a"@g' /home/$USER/.dotfiles/.config/dunst/dunstrc
    killall -e dunst & sleep 1; dunstify "Theme switched to grayscale" &
  }
  gruvbox () {
    # btop
    sed -i 's@themes/*.*@themes/gruvbox_dark_v2.theme"@g' /home/$USER/.dotfiles/.config/btop/btop.conf
    # emacs
    sed -i "s/load-theme\ '*.*/load-theme 'doom-gruvbox\ :no-confirm)/g" /home/$USER/.dotfiles/.config/emacs/init.el
    # ghostty
    sed -i 's@themes/*.*@themes/Gruvbox Dark@g' /home/$USER/.dotfiles/.config/ghostty/config
    # rofi
    sed -i 's@themes/*.*@themes/gruvbox"@g' /home/$USER/.dotfiles/.config/rofi/config.rasi
    # rmpc
    sed -i 's/theme:\ Some("*.*"),/theme:\ Some("gruvbox"),/g' /home/$USER/.dotfiles/.config/rmpc/config.ron
    # WMs
    if [ $XDG_CURRENT_DESKTOP = 'hyprland' ]; then
			sed -i 's@col.active_border*.*@col.active_border\ =\ rgba(98971aff)@g' /home/$USER/.dotfiles/.config/hypr/hyprland.conf
			sed -i 's@col.inactive_border*.*@col.inactive_border\ =\ rgba(504945ff)@g' /home/$USER/.dotfiles/.config/hypr/hyprland.conf
			sed -i 's@color*.*@color\ =\ rgba(3c3836ff)@g' /home/$USER/.dotfiles/.config/hypr/hyprland.conf
			sed -i 's@wallpapers/*.*@wallpapers/gruvbox.png@g' /home/$USER/.dotfiles/.config/hypr/hyprland.conf
			sed -i 's@wallpapers/*.*@wallpapers/gruvbox.png@g' /home/$USER/.dotfiles/.config/hypr/hyprlock.conf
			sed -i 's@themes/*.*@themes/gruvbox.css";@g' /home/$USER/.dotfiles/.config/waybar/style.css
      nohup bash -c "pkill swaybg; swaybg -i ~/.dotfiles/wallpapers/gruvbox.png &"
      nohup bash -c "killall waybar && waybar & disown"
    elif [ $XDG_CURRENT_DESKTOP = 'qtile' ]; then
			sed -i 's/themes.*\ import\ colors/themes.gruvbox\ import\ colors/g' /home/$USER/.dotfiles/.config/qtile/config.py
			sed -i 's@wallpapers/*.*@wallpapers/gruvbox.png",@g' /home/$USER/.dotfiles/.config/qtile/config.py
			sed -i 's@xresources/*.*@xresources/gruvbox"@g' /home/$USER/.dotfiles/.Xresources
      qtile cmd-obj -o cmd -f reload_config
		elif  [ $XDG_CURRENT_DESKTOP = 'mango' ]; then
			sed -i 's@themes/*.*@themes/gruvbox.conf@g' /home/$USER/.dotfiles/.config/mango/config.conf
			sed -i 's@themes/*.*@themes/gruvbox.css";@g' /home/$USER/.dotfiles/.config/waybar/style.css
      nohup bash -c "pkill swaybg; swaybg -i ~/.dotfiles/wallpapers/gruvbox.png &"
      nohup bash -c "killall waybar && waybar & disown"
    else
      echo "What?"
    fi
    # dunst
    sed -i 's@background\ =\ "#*.*@background\ =\ "#282828"@g' /home/$USER/.dotfiles/.config/dunst/dunstrc
    sed -i 's@foreground\ =\ "#*.*@foreground\ =\ "#ebdbb2"@g' /home/$USER/.dotfiles/.config/dunst/dunstrc
    sed -i 's@frame_color\ =\ "#*.*@frame_color\ =\ "#98971a"@g' /home/$USER/.dotfiles/.config/dunst/dunstrc
    killall -e dunst & sleep 1; dunstify "Theme switched to Gruvbox" &
  }
  kanagawa () {
    # btop
    sed -i 's@themes/*.*@themes/kanagawa-wave.theme"@g' /home/$USER/.dotfiles/.config/btop/btop.conf
    # emacs
    sed -i "s/load-theme\ '*.*/load-theme 'kanagawa-wave\ :no-confirm)/g" /home/$USER/.dotfiles/.config/emacs/init.el
    # ghostty
    sed -i 's@themes/*.*@themes/Kanagawa\ Wave@g' /home/$USER/.dotfiles/.config/ghostty/config
    # rofi
    sed -i 's@themes/*.*@themes/kanagawa"@g' /home/$USER/.dotfiles/.config/rofi/config.rasi
    # rmpc
    sed -i 's/theme:\ Some("*.*"),/theme:\ Some("kanagawa"),/g' /home/$USER/.dotfiles/.config/rmpc/config.ron
    # WMs
    if [ $XDG_CURRENT_DESKTOP = 'hyprland' ]; then
			sed -i 's@col.active_border*.*@col.active_border\ =\ rgba(2d4f67ff)@g' /home/$USER/.dotfiles/.config/hypr/hyprland.conf
			sed -i 's@col.inactive_border*.*@col.inactive_border\ =\ rgba(35353Dff)@g' /home/$USER/.dotfiles/.config/hypr/hyprland.conf
			sed -i 's@color*.*@color\ =\ rgba(1f1f28ff)@g' /home/$USER/.dotfiles/.config/hypr/hyprland.conf
			sed -i 's@wallpapers/*.*@wallpapers/kanagawa.png@g' /home/$USER/.dotfiles/.config/hypr/hyprland.conf
			sed -i 's@wallpapers/*.*@wallpapers/kanagawa.png@g' /home/$USER/.dotfiles/.config/hypr/hyprlock.conf
			sed -i 's@themes/*.*@themes/kanagawa.css";@g' /home/$USER/.dotfiles/.config/waybar/style.css
      nohup bash -c "pkill swaybg; swaybg -i ~/.dotfiles/wallpapers/kanagawa.png &"
      nohup bash -c "killall waybar && waybar & disown"
    elif [ $XDG_CURRENT_DESKTOP = 'qtile' ]; then
			sed -i 's/themes.*\ import\ colors/themes.kanagawa\ import\ colors/g' /home/$USER/.dotfiles/.config/qtile/config.py
			sed -i 's@wallpapers/*.*@wallpapers/kanagawa.png",@g' /home/$USER/.dotfiles/.config/qtile/config.py
			sed -i 's@xresources/*.*@xresources/kanagawa"@g' /home/$USER/.dotfiles/.Xresources
      qtile cmd-obj -o cmd -f reload_config
		elif  [ $XDG_CURRENT_DESKTOP = 'mango' ]; then
			sed -i 's@themes/*.*@themes/kanagawa.conf@g' /home/$USER/.dotfiles/.config/mango/config.conf
			sed -i 's@themes/*.*@themes/kanagawa.css";@g' /home/$USER/.dotfiles/.config/waybar/style.css
      nohup bash -c "pkill swaybg; swaybg -i ~/.dotfiles/wallpapers/kanagawa.png &"
      nohup bash -c "killall waybar && waybar & disown"
    else
      echo "What?"
    fi
    # dunst
    sed -i 's@background\ =\ "#*.*@background\ =\ "#1f1f28"@g' /home/$USER/.dotfiles/.config/dunst/dunstrc
    sed -i 's@foreground\ =\ "#*.*@foreground\ =\ "#dcd7ba"@g' /home/$USER/.dotfiles/.config/dunst/dunstrc
    sed -i 's@frame_color\ =\ "#*.*@frame_color\ =\ "#2d4f67"@g' /home/$USER/.dotfiles/.config/dunst/dunstrc
    killall -e dunst & sleep 1; dunstify "Theme switched to Kanagawa" &
  }
  onedark () {
    # btop
    sed -i 's@themes/*.*@themes/onedark.theme"@g' /home/$USER/.dotfiles/.config/btop/btop.conf
    # emacs
    sed -i "s/load-theme\ '*.*/load-theme 'doom-one\ :no-confirm)/g" /home/$USER/.dotfiles/.config/emacs/init.el
    # ghostty
    sed -i 's@themes/*.*@themes/One Half Dark@g' /home/$USER/.dotfiles/.config/ghostty/config
    # rofi
    sed -i 's@themes/*.*@themes/onedark"@g' /home/$USER/.dotfiles/.config/rofi/config.rasi
    # rmpc
    sed -i 's/theme:\ Some("*.*"),/theme:\ Some("onedark"),/g' /home/$USER/.dotfiles/.config/rmpc/config.ron
    # WMs
    if [ $XDG_CURRENT_DESKTOP = 'hyprland' ]; then
			sed -i 's@col.active_border*.*@col.active_border\ =\ rgba(61afefff)@g' /home/$USER/.dotfiles/.config/hypr/hyprland.conf
			sed -i 's@col.inactive_border*.*@col.inactive_border\ =\ rgba(848b98ff)@g' /home/$USER/.dotfiles/.config/hypr/hyprland.conf
			sed -i 's@color*.*@color\ =\ rgba(393f4aff)@g' /home/$USER/.dotfiles/.config/hypr/hyprland.conf
			sed -i 's@wallpapers/*.*@wallpapers/onedark.png@g' /home/$USER/.dotfiles/.config/hypr/hyprland.conf
			sed -i 's@wallpapers/*.*@wallpapers/onedark.png@g' /home/$USER/.dotfiles/.config/hypr/hyprlock.conf
			sed -i 's@themes/*.*@themes/onedark.css";@g' /home/$USER/.dotfiles/.config/waybar/style.css
      nohup bash -c "pkill swaybg; swaybg -i ~/.dotfiles/wallpapers/onedark.png &"
      nohup bash -c "killall waybar && waybar & disown"
    elif [ $XDG_CURRENT_DESKTOP = 'qtile' ]; then
			sed -i 's/themes.*\ import\ colors/themes.onedark\ import\ colors/g' /home/$USER/.dotfiles/.config/qtile/config.py
			sed -i 's@wallpapers/*.*@wallpapers/onedark.png",@g' /home/$USER/.dotfiles/.config/qtile/config.py
			sed -i 's@xresources/*.*@xresources/onedark"@g' /home/$USER/.dotfiles/.Xresources
      qtile cmd-obj -o cmd -f reload_config
		elif  [ $XDG_CURRENT_DESKTOP = 'mango' ]; then
			sed -i 's@themes/*.*@themes/onedark.conf@g' /home/$USER/.dotfiles/.config/mango/config.conf
			sed -i 's@themes/*.*@themes/onedark.css";@g' /home/$USER/.dotfiles/.config/waybar/style.css
      nohup bash -c "pkill swaybg; swaybg -i ~/.dotfiles/wallpapers/onedark.png &"
      nohup bash -c "killall waybar && waybar & disown"
    else
      echo "What?"
    fi
    # dunst
    sed -i 's@background\ =\ "#*.*@background\ =\ "#282c34"@g' /home/$USER/.dotfiles/.config/dunst/dunstrc
    sed -i 's@foreground\ =\ "#*.*@foreground\ =\ "#abb2bf"@g' /home/$USER/.dotfiles/.config/dunst/dunstrc
    sed -i 's@frame_color\ =\ "#*.*@frame_color\ =\ "#61afef"@g' /home/$USER/.dotfiles/.config/dunst/dunstrc
    killall -e dunst & sleep 1; dunstify "Theme switched to One Dark" &
  }
  poimandres () {
    # btop
    sed -i 's@themes/*.*@themes/poimandres.theme"@g' /home/$USER/.dotfiles/.config/btop/btop.conf
    # emacs
    sed -i "s/load-theme\ '*.*/load-theme 'poimandres\ :no-confirm)/g" /home/$USER/.dotfiles/.config/emacs/init.el
    # ghostty
    sed -i 's@themes/*.*@themes/poimandres@g' /home/$USER/.dotfiles/.config/ghostty/config
    # rofi
    sed -i 's@themes/*.*@themes/poimandres"@g' /home/$USER/.dotfiles/.config/rofi/config.rasi
    # rmpc
    sed -i 's/theme:\ Some("*.*"),/theme:\ Some("poimandres"),/g' /home/$USER/.dotfiles/.config/rmpc/config.ron
    # WMs
    if [ $XDG_CURRENT_DESKTOP = 'hyprland' ]; then
			sed -i 's@col.active_border*.*@col.active_border\ =\ rgba(5DE4C7ff)@g' /home/$USER/.dotfiles/.config/hypr/hyprland.conf
			sed -i 's@col.inactive_border*.*@col.inactive_border\ =\ rgba(3b3f4fff)@g' /home/$USER/.dotfiles/.config/hypr/hyprland.conf
			sed -i 's@color*.*@color\ =\ rgba(303340ff)@g' /home/$USER/.dotfiles/.config/hypr/hyprland.conf
			sed -i 's@wallpapers/*.*@wallpapers/poimandres.png@g' /home/$USER/.dotfiles/.config/hypr/hyprland.conf
			sed -i 's@wallpapers/*.*@wallpapers/poimandres.png@g' /home/$USER/.dotfiles/.config/hypr/hyprlock.conf
			sed -i 's@themes/*.*@themes/poimandres.css";@g' /home/$USER/.dotfiles/.config/waybar/style.css
      nohup bash -c "pkill swaybg; swaybg -i ~/.dotfiles/wallpapers/poimandres.png &"
      nohup bash -c "killall waybar && waybar & disown"
    elif [ $XDG_CURRENT_DESKTOP = 'qtile' ]; then
			sed -i 's/themes.*\ import\ colors/themes.poimandres\ import\ colors/g' /home/$USER/.dotfiles/.config/qtile/config.py
			sed -i 's@wallpapers/*.*@wallpapers/poimandres.png",@g' /home/$USER/.dotfiles/.config/qtile/config.py
			sed -i 's@xresources/*.*@xresources/poimandres"@g' /home/$USER/.dotfiles/.Xresources
      qtile cmd-obj -o cmd -f reload_config
		elif  [ $XDG_CURRENT_DESKTOP = 'mango' ]; then
			sed -i 's@themes/*.*@themes/poimandres.conf@g' /home/$USER/.dotfiles/.config/mango/config.conf
			sed -i 's@themes/*.*@themes/poimandres.css";@g' /home/$USER/.dotfiles/.config/waybar/style.css
      nohup bash -c "pkill swaybg; swaybg -i ~/.dotfiles/wallpapers/poimandres.png &"
      nohup bash -c "killall waybar && waybar & disown"
    else
      echo "What?"
    fi
    # dunst
    sed -i 's@background\ =\ "#*.*@background\ =\ "#1B1E28"@g' /home/$USER/.dotfiles/.config/dunst/dunstrc
    sed -i 's@foreground\ =\ "#*.*@foreground\ =\ "#E4F0FB"@g' /home/$USER/.dotfiles/.config/dunst/dunstrc
    sed -i 's@frame_color\ =\ "#*.*@frame_color\ =\ "#5DE4C7"@g' /home/$USER/.dotfiles/.config/dunst/dunstrc
    killall -e dunst & sleep 1; dunstify "Theme switched to Poimandres" &
  }
  spacegray () {
    # btop
    sed -i 's@themes/*.*@themes/spacegray.theme"@g' /home/$USER/.dotfiles/.config/btop/btop.conf
    # emacs
    sed -i "s/load-theme\ '*.*/load-theme 'doom-spacegrey\ :no-confirm)/g" /home/$USER/.dotfiles/.config/emacs/init.el
    # ghostty
    sed -i 's@themes/*.*@themes/Spacegray@g' /home/$USER/.dotfiles/.config/ghostty/config
    # rofi
    sed -i 's@themes/*.*@themes/spacegray"@g' /home/$USER/.dotfiles/.config/rofi/config.rasi
    # rmpc
    sed -i 's/theme:\ Some("*.*"),/theme:\ Some("spacegray"),/g' /home/$USER/.dotfiles/.config/rmpc/config.ron
    # WMs
    if [ $XDG_CURRENT_DESKTOP = 'hyprland' ]; then
			sed -i 's@col.active_border*.*@col.active_border\ =\ rgba(b04b57ff)@g' /home/$USER/.dotfiles/.config/hypr/hyprland.conf
			sed -i 's@col.inactive_border*.*@col.inactive_border\ =\ rgba(4c4f56ff)@g' /home/$USER/.dotfiles/.config/hypr/hyprland.conf
			sed -i 's@color*.*@color\ =\ rgba(363942ff)@g' /home/$USER/.dotfiles/.config/hypr/hyprland.conf
			sed -i 's@wallpapers/*.*@wallpapers/spacegray.png@g' /home/$USER/.dotfiles/.config/hypr/hyprland.conf
			sed -i 's@wallpapers/*.*@wallpapers/spacegray.png@g' /home/$USER/.dotfiles/.config/hypr/hyprlock.conf
			sed -i 's@themes/*.*@themes/spacegray.css";@g' /home/$USER/.dotfiles/.config/waybar/style.css
      nohup bash -c "pkill swaybg; swaybg -i ~/.dotfiles/wallpapers/spacegray.png &"
      nohup bash -c "killall waybar && waybar & disown"
    elif [ $XDG_CURRENT_DESKTOP = 'qtile' ]; then
			sed -i 's/themes.*\ import\ colors/themes.spacegray\ import\ colors/g' /home/$USER/.dotfiles/.config/qtile/config.py
			sed -i 's@wallpapers/*.*@wallpapers/spacegray.png",@g' /home/$USER/.dotfiles/.config/qtile/config.py
			sed -i 's@xresources/*.*@xresources/spacegray"@g' /home/$USER/.dotfiles/.Xresources
      qtile cmd-obj -o cmd -f reload_config
		elif  [ $XDG_CURRENT_DESKTOP = 'mango' ]; then
			sed -i 's@themes/*.*@themes/spacegray.conf@g' /home/$USER/.dotfiles/.config/mango/config.conf
			sed -i 's@themes/*.*@themes/spacegray.css";@g' /home/$USER/.dotfiles/.config/waybar/style.css
      nohup bash -c "pkill swaybg; swaybg -i ~/.dotfiles/wallpapers/spacegray.png &"
      nohup bash -c "killall waybar && waybar & disown"
    else
      echo "What?"
    fi
    # dunst
    sed -i 's@background\ =\ "#*.*@background\ =\ "#20242d"@g' /home/$USER/.dotfiles/.config/dunst/dunstrc
    sed -i 's@foreground\ =\ "#*.*@foreground\ =\ "#b3b8c3"@g' /home/$USER/.dotfiles/.config/dunst/dunstrc
    sed -i 's@frame_color\ =\ "#*.*@frame_color\ =\ "#b04b57"@g' /home/$USER/.dotfiles/.config/dunst/dunstrc
    killall -e dunst & sleep 1; dunstify "Theme switched to Spacegray" &
  }
  tokyonight () {
    # btop
    sed -i 's@themes/*.*@themes/tokyo-night.theme"@g' /home/$USER/.dotfiles/.config/btop/btop.conf
    # emacs
    sed -i "s/load-theme\ '*.*/load-theme 'doom-tokyo-night\ :no-confirm)/g" /home/$USER/.dotfiles/.config/emacs/init.el
    # ghostty
    sed -i 's@themes/*.*@themes/TokyoNight@g' /home/$USER/.dotfiles/.config/ghostty/config
    # rofi
    sed -i 's@themes/*.*@themes/tokyonight"@g' /home/$USER/.dotfiles/.config/rofi/config.rasi
    # rmpc
    sed -i 's/theme:\ Some("*.*"),/theme:\ Some("tokyonight"),/g' /home/$USER/.dotfiles/.config/rmpc/config.ron
    # WMs
    if [ $XDG_CURRENT_DESKTOP = 'hyprland' ]; then
			sed -i 's@col.active_border*.*@col.active_border\ =\ rgba(7aa2f7ff)@g' /home/$USER/.dotfiles/.config/hypr/hyprland.conf
			sed -i 's@col.inactive_border*.*@col.inactive_border\ =\ rgba(414868ff)@g' /home/$USER/.dotfiles/.config/hypr/hyprland.conf
			sed -i 's@color*.*@color\ =\ rgba(24283bff)@g' /home/$USER/.dotfiles/.config/hypr/hyprland.conf
			sed -i 's@wallpapers/*.*@wallpapers/tokyonight.png@g' /home/$USER/.dotfiles/.config/hypr/hyprland.conf
			sed -i 's@wallpapers/*.*@wallpapers/tokyonight.png@g' /home/$USER/.dotfiles/.config/hypr/hyprlock.conf
			sed -i 's@themes/*.*@themes/tokyonight.css";@g' /home/$USER/.dotfiles/.config/waybar/style.css
      nohup bash -c "pkill swaybg; swaybg -i ~/.dotfiles/wallpapers/tokyonight.png &"
      nohup bash -c "killall waybar && waybar & disown"
    elif [ $XDG_CURRENT_DESKTOP = 'qtile' ]; then
			sed -i 's/themes.*\ import\ colors/themes.tokyonight\ import\ colors/g' /home/$USER/.dotfiles/.config/qtile/config.py
			sed -i 's@wallpapers/*.*@wallpapers/tokyonight.png",@g' /home/$USER/.dotfiles/.config/qtile/config.py
			sed -i 's@xresources/*.*@xresources/tokyonight"@g' /home/$USER/.dotfiles/.Xresources
      qtile cmd-obj -o cmd -f reload_config
		elif  [ $XDG_CURRENT_DESKTOP = 'mango' ]; then
			sed -i 's@themes/*.*@themes/tokyonight.conf@g' /home/$USER/.dotfiles/.config/mango/config.conf
			sed -i 's@themes/*.*@themes/tokyonight.css";@g' /home/$USER/.dotfiles/.config/waybar/style.css
      nohup bash -c "pkill swaybg; swaybg -i ~/.dotfiles/wallpapers/tokyonight.png &"
      nohup bash -c "killall waybar && waybar & disown"
    else
      echo "What?"
    fi
    # dunst
    sed -i 's@background\ =\ "#*.*@background\ =\ "#1a1b26"@g' /home/$USER/.dotfiles/.config/dunst/dunstrc
    sed -i 's@foreground\ =\ "#*.*@foreground\ =\ "#a9b1d6"@g' /home/$USER/.dotfiles/.config/dunst/dunstrc
    sed -i 's@frame_color\ =\ "#*.*@frame_color\ =\ "#7aa2f7"@g' /home/$USER/.dotfiles/.config/dunst/dunstrc
    killall -e dunst & sleep 1; dunstify "Theme switched to Tokyo Night" &
  }
  declare -a options=(
  ayu
  catppuccin
  dracula
  everforest
  grayscale
  gruvbox
  kanagawa
  onedark
  poimandres
  spacegray
  tokyonight
  "quit"
  )
  choice=$(printf '%s\n' "${options[@]}" | rofi -m 1 -dmenu -i -l 20 -p 'Utilities')
  if [[ "$choice" == quit ]]; then
    echo "Program Terminated." && exit 1
  elif [ "$choice" ]; then
    cfg=$(printf '%s\n' "${choice}" | awk '{print $NF}')
    "$cfg"
  else
    echo "What?" && exit 1
  fi
}

Screenshot () {
if [ $XDG_SESSION_TYPE = 'wayland' ]; then
  sleep 1; grim -o HDMI-A-1 -l 9 -t png
  notify-send "Screenshot Taken"
elif [ $XDG_SESSION_TYPE = 'x11' ]; then
  scrot -d 1 -M 0 -q 9
  notify-send "Screenshot Taken"
else
  echo "What?"
fi
}

declare -a options=(
Screenshot
Wallpaper
Themes
"Quit"
)

choice=$(printf '%s\n' "${options[@]}" | rofi -m 1 -dmenu -i -l 20 -p 'Utilities')

if [[ "$choice" == quit ]]; then
	echo "Program Terminated." && exit 1
elif [ "$choice" ]; then
	cfg=$(printf '%s\n' "${choice}" | awk '{print $NF}')
	"$cfg"
else
	echo "Program Terminated." && exit 1
fi
